### ISSUE TITLE
Make file gives errors

### ISSUE THREAD

**Issue by Easyroomrom** [camillevuillaume/Paillier-GMP#1]
I am getting an error when entering the "make all" command
![error](https://user-images.githubusercontent.com/33297165/54701144-ca760880-4b0a-11e9-9f5c-4672da9e4f93.png)

Any help would be much appreciated. Thank you in advanced!

**Comment by camillevuillaume** [comment]
Better late than never! the current version should have fixed this issue. I did not have this problem before but it also happened on my more recent system.
